name = input("Enter you name :")
quest = input("Enter your quest :")
color = input("Enter your favorite  color :")
print("\"So your name is " + name + ", your quest is " +quest +", and your favorite color is "+color+"\"")
print(type(name))